name: "Nuestro primer workflow en github actions"

on:
  push:
    branches:
    - main
		-develop
jobs:
	
	hello-world:
		runs-on: ubuntu-latest
		steps:
			- name: Saludo
				run: echo "Hola mundo desde github actions"